const data = [
  {
    id: 1,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    closestReservation: '',
  },
  {
    id: 2,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    closestReservation: '',
  },
  {
    id: 3,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 4,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 5,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 6,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 7,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 8,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 9,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 10,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 11,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 12,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 13,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 14,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
  {
    id: 15,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
  },
]

export default data
