const data = [
  {
    id: 1,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 2,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 3,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 4,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 5,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 6,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 7,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 8,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 9,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 10,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 11,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 12,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 13,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 14,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 15,
    seats: 4,
    sector: 1,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 16,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 17,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 18,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 19,
    seats: 5,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 20,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 21,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 22,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 23,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 24,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 25,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 26,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 27,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 28,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 29,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 30,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 31,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 32,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 33,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 34,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 35,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
  {
    id: 36,
    seats: 4,
    sector: 2,
    isOccupied: false,
    isReserved: false,
    reservations: [],
    color: '#8dd84e',
  },
]

export default data
